import { Tenant, Account, JournalEntry, BankStatementLine, FixedAsset, AuditLogEvent, FxRate, CustomerInvoice, VendorBill, FiscalPeriod, TreasuryAccount, DepartmentBudget, ApprovalItem, TaxJurisdiction, EnterpriseUser, CustomRoleDefinition, CustomerContact, VendorContact, CustomAttributeDefinition, ProductServiceItem, PriceChangeHistoryEntry, InvoiceTemplate, CustomerPaymentReceipt, CustomerOpeningBalanceRecord } from './types';

export const INITIAL_TENANTS: Tenant[] = [
  {
    id: 't-acme-us',
    name: 'Acme Enterprise Inc.',
    code: 'ACME-US',
    currency: 'USD',
    country: 'United States',
    pluginId: 'us_gaap',
    organizations: [
      {
        id: 'org-acme-north',
        tenantId: 't-acme-us',
        name: 'Acme North America LLC',
        code: 'ACME-NA',
        branches: [
          { id: 'br-ny-hq', organizationId: 'org-acme-north', tenantId: 't-acme-us', name: 'New York HQ', code: 'NY-HQ' },
          { id: 'br-sf-tech', organizationId: 'org-acme-north', tenantId: 't-acme-us', name: 'San Francisco Hub', code: 'SF-HUB' },
        ],
      },
    ],
  },
  {
    id: 't-global-eu',
    name: 'TechGlobe Europe B.V.',
    code: 'GLOBE-EU',
    currency: 'EUR',
    country: 'Netherlands',
    pluginId: 'eu_ifrs',
    organizations: [
      {
        id: 'org-globe-west',
        tenantId: 't-global-eu',
        name: 'TechGlobe West Europe',
        code: 'GLOBE-WE',
        branches: [
          { id: 'br-ams-hq', organizationId: 'org-globe-west', tenantId: 't-global-eu', name: 'Amsterdam HQ', code: 'AMS-HQ' },
          { id: 'br-par-ops', organizationId: 'org-globe-west', tenantId: 't-global-eu', name: 'Paris Operations', code: 'PAR-OPS' },
        ],
      },
    ],
  },
  {
    id: 't-bharat-in',
    name: 'Bharat Retail & Tech Pvt Ltd',
    code: 'BHARAT-IN',
    currency: 'INR',
    country: 'India',
    pluginId: 'in_gst',
    organizations: [
      {
        id: 'org-bharat-south',
        tenantId: 't-bharat-in',
        name: 'Bharat Digital South',
        code: 'BHARAT-S',
        branches: [
          { id: 'br-blr-tech', organizationId: 'org-bharat-south', tenantId: 't-bharat-in', name: 'Bengaluru Tech Park', code: 'BLR-01' },
          { id: 'br-mum-fin', organizationId: 'org-bharat-south', tenantId: 't-bharat-in', name: 'Mumbai Financial Dist', code: 'MUM-01' },
        ],
      },
    ],
  },
];

export const INITIAL_ACCOUNTS: Record<string, Account[]> = {
  't-acme-us': [
    { id: 'acc-1001', tenantId: 't-acme-us', code: '1010', name: 'Operating Cash - Chase Bank', type: 'ASSET', currency: 'USD', balance: 485000 },
    { id: 'acc-1002', tenantId: 't-acme-us', code: '1100', name: 'Accounts Receivable', type: 'ASSET', currency: 'USD', balance: 142000 },
    { id: 'acc-1003', tenantId: 't-acme-us', code: '1500', name: 'Computer Equipment & Servers', type: 'ASSET', currency: 'USD', balance: 95000 },
    { id: 'acc-1004', tenantId: 't-acme-us', code: '1510', name: 'Accumulated Depreciation - Servers', type: 'ASSET', currency: 'USD', balance: -19000 },
    { id: 'acc-2001', tenantId: 't-acme-us', code: '2010', name: 'Accounts Payable', type: 'LIABILITY', currency: 'USD', balance: 64000 },
    { id: 'acc-2002', tenantId: 't-acme-us', code: '2200', name: 'State Sales Tax Payable', type: 'LIABILITY', currency: 'USD', balance: 14200 },
    { id: 'acc-3001', tenantId: 't-acme-us', code: '3010', name: 'Common Stock & Capital', type: 'EQUITY', currency: 'USD', balance: 350000 },
    { id: 'acc-3002', tenantId: 't-acme-us', code: '3200', name: 'Retained Earnings', type: 'EQUITY', currency: 'USD', balance: 114800 },
    { id: 'acc-4001', tenantId: 't-acme-us', code: '4010', name: 'SaaS Subscription Revenue', type: 'REVENUE', currency: 'USD', balance: 290000 },
    { id: 'acc-4002', tenantId: 't-acme-us', code: '4020', name: 'Enterprise Consulting Revenue', type: 'REVENUE', currency: 'USD', balance: 85000 },
    { id: 'acc-5001', tenantId: 't-acme-us', code: '5010', name: 'Cloud Infrastructure & Hosting Expenses', type: 'EXPENSE', currency: 'USD', balance: 45000 },
    { id: 'acc-5002', tenantId: 't-acme-us', code: '5020', name: 'Engineering & Staff Salaries', type: 'EXPENSE', currency: 'USD', balance: 125000 },
    { id: 'acc-5003', tenantId: 't-acme-us', code: '5030', name: 'Depreciation Expense', type: 'EXPENSE', currency: 'USD', balance: 25000 },
  ],
  't-global-eu': [
    { id: 'acc-e101', tenantId: 't-global-eu', code: '1010', name: 'ING Bank EUR Main', type: 'ASSET', currency: 'EUR', balance: 620000 },
    { id: 'acc-e102', tenantId: 't-global-eu', code: '1100', name: 'Trade Debtors (Accounts Receivable)', type: 'ASSET', currency: 'EUR', balance: 185000 },
    { id: 'acc-e201', tenantId: 't-global-eu', code: '2010', name: 'Trade Creditors (Accounts Payable)', type: 'LIABILITY', currency: 'EUR', balance: 72000 },
    { id: 'acc-e202', tenantId: 't-global-eu', code: '2100', name: 'EU VAT Payable (21% Standard Rate)', type: 'LIABILITY', currency: 'EUR', balance: 38850 },
    { id: 'acc-e203', tenantId: 't-global-eu', code: '2110', name: 'EU Reverse Charge VAT Input Credit', type: 'ASSET', currency: 'EUR', balance: 12400 },
    { id: 'acc-e301', tenantId: 't-global-eu', code: '3010', name: 'Share Capital', type: 'EQUITY', currency: 'EUR', balance: 400000 },
    { id: 'acc-e401', tenantId: 't-global-eu', code: '4010', name: 'Cross-Border EU Software Sales', type: 'REVENUE', currency: 'EUR', balance: 380000 },
    { id: 'acc-e501', tenantId: 't-global-eu', code: '5010', name: 'Research & Development Costs', type: 'EXPENSE', currency: 'EUR', balance: 73450 },
  ],
  't-bharat-in': [
    { id: 'acc-i101', tenantId: 't-bharat-in', code: '1010', name: 'HDFC Current Account', type: 'ASSET', currency: 'INR', balance: 14500000 },
    { id: 'acc-i102', tenantId: 't-bharat-in', code: '1100', name: 'Trade Receivables', type: 'ASSET', currency: 'INR', balance: 4200000 },
    { id: 'acc-i201', tenantId: 't-bharat-in', code: '2010', name: 'Trade Payables', type: 'LIABILITY', currency: 'INR', balance: 1800000 },
    { id: 'acc-i202', tenantId: 't-bharat-in', code: '2201', name: 'CGST Payable (9%)', type: 'LIABILITY', currency: 'INR', balance: 378000 },
    { id: 'acc-i203', tenantId: 't-bharat-in', code: '2202', name: 'SGST Payable (9%)', type: 'LIABILITY', currency: 'INR', balance: 378000 },
    { id: 'acc-i204', tenantId: 't-bharat-in', code: '2203', name: 'IGST Payable (18% Inter-State)', type: 'LIABILITY', currency: 'INR', balance: 216000 },
    { id: 'acc-i205', tenantId: 't-bharat-in', code: '1301', name: 'Input Tax Credit (ITC) - GST', type: 'ASSET', currency: 'INR', balance: 180000 },
    { id: 'acc-i301', tenantId: 't-bharat-in', code: '3010', name: 'Paid Up Equity Capital', type: 'EQUITY', currency: 'INR', balance: 10000000 },
    { id: 'acc-i401', tenantId: 't-bharat-in', code: '4010', name: 'Domestic Enterprise Tech Sales', type: 'REVENUE', currency: 'INR', balance: 8000000 },
    { id: 'acc-i501', tenantId: 't-bharat-in', code: '5010', name: 'Office Operations & Server Maintenance', type: 'EXPENSE', currency: 'INR', balance: 1892000 },
  ],
};

export const INITIAL_JOURNAL_ENTRIES: JournalEntry[] = [
  {
    id: 'je-1001',
    entryNumber: 'JE-2026-0001',
    tenantId: 't-acme-us',
    organizationId: 'org-acme-north',
    branchId: 'br-ny-hq',
    date: '2026-08-01',
    description: 'Q3 Enterprise SaaS Subscription Invoice #INV-9821',
    reference: 'INV-9821',
    pluginId: 'us_gaap',
    postedBy: 'sarah.accountant@acme.com',
    postedRole: 'accountant',
    status: 'POSTED',
    lines: [
      { id: 'jl-1', accountId: 'acc-1002', accountCode: '1100', accountName: 'Accounts Receivable', debit: 110000, credit: 0, memo: 'Client Invoice' },
      { id: 'jl-2', accountId: 'acc-4001', accountCode: '4010', accountName: 'SaaS Subscription Revenue', debit: 0, credit: 100000, memo: 'Net Revenue' },
      { id: 'jl-3', accountId: 'acc-2002', accountCode: '2200', accountName: 'State Sales Tax Payable', debit: 0, credit: 10000, memo: '10% NY Sales Tax' },
    ],
    totalDebit: 110000,
    totalCredit: 110000,
    createdAt: '2026-08-01T10:15:00Z',
  },
  {
    id: 'je-1002',
    entryNumber: 'JE-2026-0002',
    tenantId: 't-acme-us',
    organizationId: 'org-acme-north',
    branchId: 'br-sf-tech',
    date: '2026-08-05',
    description: 'AWS Cloud Infrastructure Monthly Hosting Settlement',
    reference: 'PO-AWS-882',
    pluginId: 'us_gaap',
    postedBy: 'john.admin@acme.com',
    postedRole: 'admin',
    status: 'POSTED',
    lines: [
      { id: 'jl-4', accountId: 'acc-5001', accountCode: '5010', accountName: 'Cloud Infrastructure Expenses', debit: 25000, credit: 0, memo: 'AWS Cloud Usage' },
      { id: 'jl-5', accountId: 'acc-1001', accountCode: '1010', accountName: 'Operating Cash - Chase Bank', debit: 0, credit: 25000, memo: 'Direct Bank Debit' },
    ],
    totalDebit: 25000,
    totalCredit: 25000,
    createdAt: '2026-08-05T14:30:00Z',
  },
  {
    id: 'je-e101',
    entryNumber: 'JE-EU-2026-001',
    tenantId: 't-global-eu',
    organizationId: 'org-globe-west',
    branchId: 'br-ams-hq',
    date: '2026-08-02',
    description: 'B2B Software Licensing - EU Cross Border Customer',
    reference: 'EU-INV-401',
    pluginId: 'eu_ifrs',
    postedBy: 'marco.finance@techglobe.eu',
    postedRole: 'accountant',
    status: 'POSTED',
    lines: [
      { id: 'jl-e1', accountId: 'acc-e102', accountCode: '1100', accountName: 'Trade Debtors', debit: 121000, credit: 0 },
      { id: 'jl-e2', accountId: 'acc-e401', accountCode: '4010', accountName: 'Cross-Border EU Software Sales', debit: 0, credit: 100000 },
      { id: 'jl-e3', accountId: 'acc-e202', accountCode: '2100', accountName: 'EU VAT Payable (21%)', debit: 0, credit: 21000 },
    ],
    totalDebit: 121000,
    totalCredit: 121000,
    createdAt: '2026-08-02T11:00:00Z',
  },
  {
    id: 'je-i101',
    entryNumber: 'JE-IN-2026-001',
    tenantId: 't-bharat-in',
    organizationId: 'org-bharat-south',
    branchId: 'br-blr-tech',
    date: '2026-08-03',
    description: 'Enterprise ERP Implementation Contract - Domestic Sales',
    reference: 'GST-INV-8891',
    pluginId: 'in_gst',
    postedBy: 'priya.ca@bharat.in',
    postedRole: 'accountant',
    status: 'POSTED',
    lines: [
      { id: 'jl-i1', accountId: 'acc-i102', accountCode: '1100', accountName: 'Trade Receivables', debit: 2360000, credit: 0 },
      { id: 'jl-i2', accountId: 'acc-i401', accountCode: '4010', accountName: 'Domestic Enterprise Tech Sales', debit: 0, credit: 2000000 },
      { id: 'jl-i3', accountId: 'acc-i202', accountCode: '2201', accountName: 'CGST Payable (9%)', debit: 0, credit: 180000 },
      { id: 'jl-i4', accountId: 'acc-i203', accountCode: '2202', accountName: 'SGST Payable (9%)', debit: 0, credit: 180000 },
    ],
    totalDebit: 2360000,
    totalCredit: 2360000,
    createdAt: '2026-08-03T16:20:00Z',
  },
];

export const INITIAL_BANK_STATEMENTS: BankStatementLine[] = [
  { id: 'bs-101', tenantId: 't-acme-us', date: '2026-08-02', description: 'Wire Transfer In - Client SaaS Payment', amount: 110000, reference: 'INV-9821', reconciled: true, matchedJournalEntryId: 'je-1001', matchedJournalLineId: 'jl-1' },
  { id: 'bs-102', tenantId: 't-acme-us', date: '2026-08-05', description: 'ACH Direct Debit - AWS Cloud Services', amount: -25000, reference: 'PO-AWS-882', reconciled: true, matchedJournalEntryId: 'je-1002', matchedJournalLineId: 'jl-5' },
  { id: 'bs-103', tenantId: 't-acme-us', date: '2026-08-10', description: 'Unassigned Deposit - Client Corp Deposit', amount: 45000, reference: 'DEP-9012', reconciled: false },
  { id: 'bs-104', tenantId: 't-acme-us', date: '2026-08-12', description: 'Office Depot Office Supplies', amount: -1450, reference: 'CARD-4412', reconciled: false },
];

export const INITIAL_FIXED_ASSETS: FixedAsset[] = [
  { id: 'fa-101', tenantId: 't-acme-us', assetNumber: 'AST-2025-01', name: 'High Performance GPU AI Cluster', category: 'IT Servers', acquisitionDate: '2025-01-15', cost: 120000, salvageValue: 20000, usefulLifeYears: 4, accumulatedDepreciation: 25000, netBookValue: 95000, depreciationMethod: 'STRAIGHT_LINE', lastDepreciationDate: '2026-07-31' },
  { id: 'fa-102', tenantId: 't-acme-us', assetNumber: 'AST-2025-02', name: 'New York HQ Executive Office Furniture', category: 'Furniture & Fixtures', acquisitionDate: '2025-03-01', cost: 35000, salvageValue: 5000, usefulLifeYears: 7, accumulatedDepreciation: 6428, netBookValue: 28572, depreciationMethod: 'STRAIGHT_LINE', lastDepreciationDate: '2026-07-31' },
];

export const INITIAL_AUDIT_LOGS: AuditLogEvent[] = [
  {
    id: 'log-101',
    timestamp: '2026-08-13T00:01:00Z',
    action: 'POST_JOURNAL',
    tenantId: 't-acme-us',
    organizationId: 'org-acme-north',
    branchId: 'br-ny-hq',
    userRole: 'accountant',
    userEmail: 'sarah.accountant@acme.com',
    details: 'Posted Journal Entry JE-2026-0001 ($110,000.00)',
    status: 'SUCCESS',
    ipAddress: '192.168.1.104',
    payloadSummary: 'Debit: 110000 | Credit: 110000 | Double-Entry Verified',
  },
  {
    id: 'log-102',
    timestamp: '2026-08-12T18:40:00Z',
    action: 'POST_JOURNAL',
    tenantId: 't-acme-us',
    userRole: 'viewer',
    userEmail: 'guest.viewer@acme.com',
    details: 'Attempted to post manual journal entry without accountant/admin role',
    status: 'FORBIDDEN',
    ipAddress: '10.0.4.12',
    payloadSummary: 'HTTP 403 - Role viewer lacks permission for write endpoints',
  },
  {
    id: 'log-103',
    timestamp: '2026-08-11T14:10:00Z',
    action: 'IMPORT_TRANSACTIONS',
    tenantId: 't-acme-us',
    userRole: 'admin',
    userEmail: 'john.admin@acme.com',
    details: 'Batch uploaded 12 journal entries via CSV importer',
    status: 'SUCCESS',
    ipAddress: '172.16.0.44',
    payloadSummary: 'Batch Size: 12 entries | Validated against Chart of Accounts',
  },
];

export const FX_RATES: FxRate[] = [
  { fromCurrency: 'EUR', toCurrency: 'USD', rate: 1.0925, asOfDate: '2026-08-12' },
  { fromCurrency: 'INR', toCurrency: 'USD', rate: 0.01205, asOfDate: '2026-08-12' },
  { fromCurrency: 'GBP', toCurrency: 'USD', rate: 1.2840, asOfDate: '2026-08-12' },
];

export const INITIAL_INVOICES: CustomerInvoice[] = [
  // 1. Prior FY Opening Outstanding Balance Invoices
  {
    id: 'inv-op-101',
    invoiceNumber: 'OPN-2026-001',
    tenantId: 't-acme-us',
    customerId: 'cust-corp-104',
    customerName: 'Vanguard Global Financial LLC',
    customerEmail: 'finance.ap@vanguardglobal.com',
    issueDate: '2026-03-15',
    dueDate: '2026-04-15',
    currency: 'USD',
    items: [
      { description: 'Prior FY Q4 Dedicated Cloud Hosting & High-Volume SLA Support', quantity: 1, unitPrice: 48000, amount: 48000, taxRate: 0 },
    ],
    subtotal: 48000,
    taxTotal: 0,
    totalAmount: 48000,
    amountPaid: 20000,
    status: 'PARTIALLY_PAID',
    revenueAccountCode: '3010',
    isOpeningBalance: true,
    fiscalYearOpening: 'FY 2026-2027',
    offsetAccountCode: '3010',
    notes: 'Outstanding balance carried forward from prior Financial Year FY 2025-2026 close.',
  },
  {
    id: 'inv-op-102',
    invoiceNumber: 'OPN-2026-002',
    tenantId: 't-acme-us',
    customerId: 'cust-hs-101',
    customerName: 'Alexander Sterling (Flat A-402)',
    customerEmail: 'a.sterling@residence.emerald.org',
    issueDate: '2026-03-01',
    dueDate: '2026-03-15',
    currency: 'USD',
    items: [
      { description: 'Prior FY Q4 Society Maintenance & Clubhouse Special Sinking Fund', quantity: 1, unitPrice: 3625, amount: 3625, taxRate: 0 },
    ],
    subtotal: 3625,
    taxTotal: 0,
    totalAmount: 3625,
    amountPaid: 0,
    status: 'OVERDUE',
    revenueAccountCode: '3010',
    isOpeningBalance: true,
    fiscalYearOpening: 'FY 2026-2027',
    offsetAccountCode: '3010',
    notes: 'Opening FY 2026-2027 carryforward arrears for Flat A-402.',
  },
  {
    id: 'inv-op-103',
    invoiceNumber: 'OPN-2026-003',
    tenantId: 't-acme-us',
    customerId: 'cust-sc-102',
    customerName: 'Maya Lin (Guardian: Richard Lin)',
    customerEmail: 'richard.lin@parentmail.com',
    issueDate: '2026-03-20',
    dueDate: '2026-04-10',
    currency: 'USD',
    items: [
      { description: 'Grade 10 Final Term STEM Lab & Robotics Kit Balance', quantity: 1, unitPrice: 1850, amount: 1850, taxRate: 0 },
    ],
    subtotal: 1850,
    taxTotal: 0,
    totalAmount: 1850,
    amountPaid: 1850,
    status: 'PAID',
    revenueAccountCode: '3010',
    isOpeningBalance: true,
    fiscalYearOpening: 'FY 2026-2027',
    offsetAccountCode: '3010',
    notes: 'Opening FY carryforward - settled on 2026-04-05.',
  },
  // 2. Current Period Invoices
  {
    id: 'inv-1001',
    invoiceNumber: 'INV-2026-001',
    tenantId: 't-acme-us',
    customerId: 'cust-corp-105',
    customerName: 'Starlight Financial Corp',
    customerEmail: 'billing@starlight.com',
    issueDate: '2026-08-01',
    dueDate: '2026-08-31',
    currency: 'USD',
    items: [
      { description: 'Enterprise SaaS Annual Platform License', quantity: 1, unitPrice: 100000, amount: 100000, taxRate: 10 },
    ],
    subtotal: 100000,
    taxTotal: 10000,
    totalAmount: 110000,
    amountPaid: 110000,
    status: 'PAID',
    revenueAccountCode: '4010',
  },
  {
    id: 'inv-1002',
    invoiceNumber: 'INV-2026-002',
    tenantId: 't-acme-us',
    customerId: 'cust-corp-106',
    customerName: 'Apex Logistics Inc',
    customerEmail: 'ap@apexlogistics.com',
    issueDate: '2026-08-08',
    dueDate: '2026-09-07',
    currency: 'USD',
    items: [
      { description: 'Cloud Audit Automation Services', quantity: 1, unitPrice: 32000, amount: 32000, taxRate: 10 },
    ],
    subtotal: 32000,
    taxTotal: 3200,
    totalAmount: 35200,
    amountPaid: 0,
    status: 'UNPAID',
    revenueAccountCode: '4020',
  },
  {
    id: 'inv-1003',
    invoiceNumber: 'INV-2026-003',
    tenantId: 't-acme-us',
    customerId: 'cust-corp-104',
    customerName: 'Vanguard Global Financial LLC',
    customerEmail: 'finance.ap@vanguardglobal.com',
    issueDate: '2026-08-02',
    dueDate: '2026-09-15',
    currency: 'USD',
    items: [
      { description: 'Q3 Enterprise Multi-Tenant Core License (25 Seats)', quantity: 25, unitPrice: 2400, amount: 60000, taxRate: 10 },
      { description: 'Custom SSO & Audit Log Pipeline Integration', quantity: 1, unitPrice: 15000, amount: 15000, taxRate: 10 },
    ],
    subtotal: 75000,
    taxTotal: 7500,
    totalAmount: 82500,
    amountPaid: 40000,
    status: 'PARTIALLY_PAID',
    revenueAccountCode: '4010',
  },
  {
    id: 'inv-1004',
    invoiceNumber: 'INV-2026-004',
    tenantId: 't-acme-us',
    customerId: 'cust-hs-101',
    customerName: 'Alexander Sterling (Flat A-402)',
    customerEmail: 'a.sterling@residence.emerald.org',
    issueDate: '2026-08-01',
    dueDate: '2026-08-15',
    currency: 'USD',
    items: [
      { description: 'Monthly Society Maintenance - August 2026 (1,450 sq ft)', quantity: 1450, unitPrice: 2.50, amount: 3625, taxRate: 0 },
      { description: 'Covered Parking Bay 1 & 2 Fee', quantity: 2, unitPrice: 100, amount: 200, taxRate: 0 },
    ],
    subtotal: 3825,
    taxTotal: 0,
    totalAmount: 3825,
    amountPaid: 0,
    status: 'UNPAID',
    revenueAccountCode: '4010',
  },
  {
    id: 'inv-1005',
    invoiceNumber: 'INV-2026-005',
    tenantId: 't-acme-us',
    customerId: 'cust-hp-103',
    customerName: 'Eleanor Vance (Patient MRN-90452)',
    customerEmail: 'evance.family@caremail.org',
    issueDate: '2026-08-05',
    dueDate: '2026-08-15',
    currency: 'USD',
    items: [
      { description: 'Deluxe Inpatient Ward Accommodations (5 Days)', quantity: 5, unitPrice: 850, amount: 4250, taxRate: 0 },
      { description: 'Cardiac Diagnostics & Ultrasound Telemetry', quantity: 1, unitPrice: 3800, amount: 3800, taxRate: 0 },
    ],
    subtotal: 8050,
    taxTotal: 0,
    totalAmount: 8050,
    amountPaid: 6440,
    status: 'PARTIALLY_PAID',
    revenueAccountCode: '4010',
    notes: '80% TPA insurance paid ($6,440.00). Co-pay balance pending: $1,610.00.',
  },
];

export const INITIAL_OPENING_BALANCES: CustomerOpeningBalanceRecord[] = [
  {
    id: 'opb-101',
    tenantId: 't-acme-us',
    customerId: 'cust-corp-104',
    customerName: 'Vanguard Global Financial LLC',
    customerCode: 'CUST-ACME-90',
    fiscalYear: 'FY 2026-2027',
    asOfDate: '2026-04-01',
    originalInvoiceNumber: 'OPN-2026-001',
    originalInvoiceDate: '2026-03-15',
    dueDate: '2026-04-15',
    originalAmount: 48000,
    amountPaid: 20000,
    currentBalance: 28000,
    offsetAccountCode: '3010',
    invoiceId: 'inv-op-101',
    notes: 'Prior FY Cloud SLA retainer carryforward. Partial payment of $20,000 received in April.',
    createdAt: '2026-04-01T09:00:00Z',
  },
  {
    id: 'opb-102',
    tenantId: 't-acme-us',
    customerId: 'cust-hs-101',
    customerName: 'Alexander Sterling (Flat A-402)',
    customerCode: 'RES-A402',
    fiscalYear: 'FY 2026-2027',
    asOfDate: '2026-04-01',
    originalInvoiceNumber: 'OPN-2026-002',
    originalInvoiceDate: '2026-03-01',
    dueDate: '2026-03-15',
    originalAmount: 3625,
    amountPaid: 0,
    currentBalance: 3625,
    offsetAccountCode: '3010',
    invoiceId: 'inv-op-102',
    notes: 'Prior FY Q4 Society Maintenance arrears for Flat A-402.',
    createdAt: '2026-04-01T09:00:00Z',
  },
  {
    id: 'opb-103',
    tenantId: 't-acme-us',
    customerId: 'cust-sc-102',
    customerName: 'Maya Lin (Guardian: Richard Lin)',
    customerCode: 'STU-2026-88',
    fiscalYear: 'FY 2026-2027',
    asOfDate: '2026-04-01',
    originalInvoiceNumber: 'OPN-2026-003',
    originalInvoiceDate: '2026-03-20',
    dueDate: '2026-04-10',
    originalAmount: 1850,
    amountPaid: 1850,
    currentBalance: 0,
    offsetAccountCode: '3010',
    invoiceId: 'inv-op-103',
    notes: 'Prior FY Grade 10 Final Term STEM Lab fee - settled in full.',
    createdAt: '2026-04-01T09:00:00Z',
  },
];

export const INITIAL_PAYMENT_RECEIPTS: CustomerPaymentReceipt[] = [
  {
    id: 'rct-1001',
    receiptNumber: 'RCT-2026-001',
    tenantId: 't-acme-us',
    customerId: 'cust-corp-105',
    customerName: 'Starlight Financial Corp',
    customerEmail: 'billing@starlight.com',
    paymentDate: '2026-08-02',
    paymentMethod: 'BANK_TRANSFER',
    bankAccountId: 'acc-1001',
    bankAccountName: 'Operating Cash - JPMorgan Chase',
    referenceNumber: 'WIRE-STRL-99410',
    totalAmountReceived: 110000,
    allocatedAmount: 110000,
    unallocatedCreditAmount: 0,
    allocations: [
      { invoiceId: 'inv-1001', invoiceNumber: 'INV-2026-001', allocatedAmount: 110000 },
    ],
    notes: 'Full payment received for SaaS Annual License INV-2026-001.',
    createdAt: '2026-08-02T11:00:00Z',
    status: 'POSTED',
  },
  {
    id: 'rct-1002',
    receiptNumber: 'RCT-2026-002',
    tenantId: 't-acme-us',
    customerId: 'cust-corp-104',
    customerName: 'Vanguard Global Financial LLC',
    customerEmail: 'finance.ap@vanguardglobal.com',
    paymentDate: '2026-04-14',
    paymentMethod: 'ACH',
    bankAccountId: 'acc-1001',
    bankAccountName: 'Operating Cash - JPMorgan Chase',
    referenceNumber: 'ACH-VANG-88210',
    totalAmountReceived: 20000,
    allocatedAmount: 20000,
    unallocatedCreditAmount: 0,
    allocations: [
      { invoiceId: 'inv-op-101', invoiceNumber: 'OPN-2026-001', allocatedAmount: 20000 },
    ],
    notes: 'Partial settlement against opening outstanding balance invoice OPN-2026-001.',
    createdAt: '2026-04-14T15:30:00Z',
    status: 'POSTED',
  },
  {
    id: 'rct-1003',
    receiptNumber: 'RCT-2026-003',
    tenantId: 't-acme-us',
    customerId: 'cust-corp-104',
    customerName: 'Vanguard Global Financial LLC',
    customerEmail: 'finance.ap@vanguardglobal.com',
    paymentDate: '2026-08-10',
    paymentMethod: 'BANK_TRANSFER',
    bankAccountId: 'acc-1001',
    bankAccountName: 'Operating Cash - JPMorgan Chase',
    referenceNumber: 'WIRE-VANG-77412',
    totalAmountReceived: 40000,
    allocatedAmount: 40000,
    unallocatedCreditAmount: 0,
    allocations: [
      { invoiceId: 'inv-1003', invoiceNumber: 'INV-2026-003', allocatedAmount: 40000 },
    ],
    notes: 'Advance installment towards Q3 Enterprise License invoice INV-2026-003.',
    createdAt: '2026-08-10T14:20:00Z',
    status: 'POSTED',
  },
  {
    id: 'rct-1004',
    receiptNumber: 'RCT-2026-004',
    tenantId: 't-acme-us',
    customerId: 'cust-sc-102',
    customerName: 'Maya Lin (Guardian: Richard Lin)',
    customerEmail: 'richard.lin@parentmail.com',
    paymentDate: '2026-04-05',
    paymentMethod: 'CREDIT_CARD',
    bankAccountId: 'acc-1001',
    bankAccountName: 'Operating Cash - JPMorgan Chase',
    referenceNumber: 'AUTH-CC-9941-VISA',
    totalAmountReceived: 1850,
    allocatedAmount: 1850,
    unallocatedCreditAmount: 0,
    allocations: [
      { invoiceId: 'inv-op-103', invoiceNumber: 'OPN-2026-003', allocatedAmount: 1850 },
    ],
    notes: 'Online portal credit card clearance of opening FY balance OPN-2026-003.',
    createdAt: '2026-04-05T10:15:00Z',
    status: 'POSTED',
  },
  {
    id: 'rct-1005',
    receiptNumber: 'RCT-2026-005',
    tenantId: 't-acme-us',
    customerId: 'cust-hp-103',
    customerName: 'Eleanor Vance (Patient MRN-90452)',
    customerEmail: 'evance.family@caremail.org',
    paymentDate: '2026-08-08',
    paymentMethod: 'ACH',
    bankAccountId: 'acc-1001',
    bankAccountName: 'Operating Cash - JPMorgan Chase',
    referenceNumber: 'BLUE-CROSS-EFT-99120',
    totalAmountReceived: 6440,
    allocatedAmount: 6440,
    unallocatedCreditAmount: 0,
    allocations: [
      { invoiceId: 'inv-1005', invoiceNumber: 'INV-2026-005', allocatedAmount: 6440 },
    ],
    notes: 'Blue Cross TPA Direct Electronic Claim Reimbursement (80% coverage).',
    createdAt: '2026-08-08T16:45:00Z',
    status: 'POSTED',
  },
];

export const INITIAL_BILLS: VendorBill[] = [
  {
    id: 'bill-2001',
    billNumber: 'BILL-AWS-8812',
    tenantId: 't-acme-us',
    vendorName: 'Amazon Web Services Inc.',
    billDate: '2026-08-01',
    dueDate: '2026-08-15',
    currency: 'USD',
    items: [
      { description: 'US East EC2 & RDS Infrastructure Hosting', amount: 25000, expenseAccountCode: '5010' },
    ],
    totalAmount: 25000,
    amountPaid: 25000,
    status: 'PAID',
  },
  {
    id: 'bill-2002',
    billNumber: 'BILL-SNOW-901',
    tenantId: 't-acme-us',
    vendorName: 'Snowflake Data Cloud',
    billDate: '2026-08-05',
    dueDate: '2026-08-25',
    currency: 'USD',
    items: [
      { description: 'Enterprise Data Warehouse Usage & Credits', amount: 18500, expenseAccountCode: '5010' },
    ],
    totalAmount: 18500,
    amountPaid: 0,
    status: 'APPROVED',
  },
];

export const INITIAL_FISCAL_PERIODS: FiscalPeriod[] = [
  { id: 'fp-2026-q1', tenantId: 't-acme-us', periodName: '2026 Q1 Fiscal Quarter', startDate: '2026-01-01', endDate: '2026-03-31', status: 'CLOSED' },
  { id: 'fp-2026-q2', tenantId: 't-acme-us', periodName: '2026 Q2 Fiscal Quarter', startDate: '2026-04-01', endDate: '2026-06-30', status: 'LOCKED' },
  { id: 'fp-2026-q3', tenantId: 't-acme-us', periodName: '2026 Q3 Fiscal Quarter', startDate: '2026-07-01', endDate: '2026-09-30', status: 'OPEN' },
  { id: 'fp-2026-q4', tenantId: 't-acme-us', periodName: '2026 Q4 Fiscal Quarter', startDate: '2026-10-01', endDate: '2026-12-31', status: 'OPEN' },
];

export const INITIAL_TREASURY_ACCOUNTS: TreasuryAccount[] = [
  { id: 'tr-101', tenantId: 't-acme-us', name: 'JPMorgan Chase Commercial Checking', accountNumber: '•••• 8821', bankName: 'JPMorgan Chase Bank N.A.', currency: 'USD', balance: 1450000, type: 'CHECKING' },
  { id: 'tr-102', tenantId: 't-acme-us', name: 'Goldman Sachs High-Yield Treasury Vault', accountNumber: '•••• 4091', bankName: 'Goldman Sachs Bank USA', currency: 'USD', balance: 3500000, type: 'MONEY_MARKET' },
  { id: 'tr-103', tenantId: 't-acme-us', name: 'Barclays International FX Reserve', accountNumber: '•••• 1109', bankName: 'Barclays Bank PLC', currency: 'EUR', balance: 850000, type: 'FX_RESERVE' },
];

export const INITIAL_DEPARTMENT_BUDGETS: DepartmentBudget[] = [
  { id: 'bgt-101', tenantId: 't-acme-us', department: 'Engineering & R&D', annualBudget: 850000, ytdActual: 320000, variance: 530000, variancePercentage: 62.3, status: 'ON_TRACK' },
  { id: 'bgt-102', tenantId: 't-acme-us', department: 'Sales & Marketing', annualBudget: 600000, ytdActual: 480000, variance: 120000, variancePercentage: 20.0, status: 'WARNING' },
  { id: 'bgt-103', tenantId: 't-acme-us', department: 'General & Administrative', annualBudget: 350000, ytdActual: 180000, variance: 170000, variancePercentage: 48.5, status: 'ON_TRACK' },
  { id: 'bgt-104', tenantId: 't-acme-us', department: 'Customer Operations', annualBudget: 250000, ytdActual: 265000, variance: -15000, variancePercentage: -6.0, status: 'EXCEEDED' },
];

export const INITIAL_APPROVAL_ITEMS: ApprovalItem[] = [
  { id: 'app-301', tenantId: 't-acme-us', entityType: 'JOURNAL_ENTRY', referenceNumber: 'JE-2026-0089', amount: 150000, currency: 'USD', description: 'Acquisition of Datacenter Hardware Assets', requestedBy: 'sarah.accountant@acme.com', requestedDate: '2026-08-10', status: 'PENDING' },
  { id: 'app-302', tenantId: 't-acme-us', entityType: 'VENDOR_BILL', referenceNumber: 'BILL-GCP-9021', amount: 42000, currency: 'USD', description: 'Google Cloud Platform Monthly Compute Bill', requestedBy: 'john.admin@acme.com', requestedDate: '2026-08-11', status: 'PENDING' },
  { id: 'app-303', tenantId: 't-acme-us', entityType: 'INVOICE', referenceNumber: 'INV-2026-012', amount: 85000, currency: 'USD', description: 'Custom Enterprise Software Licensing Agreement', requestedBy: 'sarah.accountant@acme.com', requestedDate: '2026-08-08', status: 'APPROVED' },
];

export const INITIAL_TAX_JURISDICTIONS: TaxJurisdiction[] = [
  { id: 'tx-101', tenantId: 't-acme-us', code: 'US-NY-TAX', name: 'New York State & City Sales Tax', taxType: 'SALES_TAX', ratePercent: 8.875, filingFrequency: 'MONTHLY', ytdAccruedTax: 42500 },
  { id: 'tx-102', tenantId: 't-acme-us', code: 'US-CA-TAX', name: 'California State Board of Equalization', taxType: 'SALES_TAX', ratePercent: 7.25, filingFrequency: 'QUARTERLY', ytdAccruedTax: 31000 },
  { id: 'tx-103', tenantId: 't-global-eu', code: 'EU-NL-VAT', name: 'Netherlands Belastingdienst VAT', taxType: 'VAT', ratePercent: 21.0, filingFrequency: 'QUARTERLY', ytdAccruedTax: 88400 },
  { id: 'tx-104', tenantId: 't-ind-corp', code: 'IN-GST-18', name: 'India Central GST (CGST/SGST)', taxType: 'GST', ratePercent: 18.0, filingFrequency: 'MONTHLY', ytdAccruedTax: 1250000 },
];

export const INITIAL_CUSTOM_ROLES: CustomRoleDefinition[] = [
  {
    id: 'role-superuser',
    name: 'Global System Super Admin',
    code: 'super_user',
    description: 'Unrestricted global authority to manage system users, appoint Entity Admins across any entity, and grant global access.',
    isSystemRole: true,
    permissions: [
      'journals:create', 'journals:post', 'journals:reverse', 'ar:manage', 'ap:manage',
      'treasury:sweep', 'fpa:budget_edit', 'governance:approve', 'tax:settle',
      'fiscal:lock_period', 'fiscal:year_end_close', 'users:manage_provisioning',
      'users:manage_global', 'users:manage_entity', 'reports:export'
    ],
  },
  {
    id: 'role-entityadmin',
    name: 'Entity Administrator',
    code: 'entity_admin',
    description: 'Entity-level administrator with authority to manage and provision user access within their assigned organization/entity.',
    isSystemRole: true,
    permissions: [
      'journals:create', 'journals:post', 'journals:reverse', 'ar:manage', 'ap:manage',
      'treasury:sweep', 'fpa:budget_edit', 'governance:approve', 'tax:settle',
      'fiscal:lock_period', 'users:manage_provisioning', 'users:manage_entity', 'reports:export'
    ],
  },
  {
    id: 'role-admin',
    name: 'Global Financial Administrator',
    code: 'admin',
    description: 'Unrestricted financial system privileges including tenant creation, role assignments, and period closes.',
    isSystemRole: true,
    permissions: [
      'journals:create', 'journals:post', 'journals:reverse', 'ar:manage', 'ap:manage',
      'treasury:sweep', 'fpa:budget_edit', 'governance:approve', 'tax:settle',
      'fiscal:lock_period', 'fiscal:year_end_close', 'users:manage_provisioning', 'reports:export'
    ],
  },
  {
    id: 'role-controller',
    name: 'Corporate Financial Controller',
    code: 'controller',
    description: 'Financial sign-off authority, period locks, year-end closes, and high-value approvals.',
    isSystemRole: true,
    permissions: [
      'journals:create', 'journals:post', 'journals:reverse', 'ar:manage', 'ap:manage',
      'treasury:sweep', 'fpa:budget_edit', 'governance:approve', 'tax:settle',
      'fiscal:lock_period', 'fiscal:year_end_close', 'reports:export'
    ],
  },
  {
    id: 'role-senior-accountant',
    name: 'Senior GL Accountant',
    code: 'accountant',
    description: 'Post and reverse journal entries, manage AR/AP sub-ledgers, and run bank reconciliations.',
    isSystemRole: true,
    permissions: [
      'journals:create', 'journals:post', 'journals:reverse', 'ar:manage', 'ap:manage',
      'treasury:sweep', 'fpa:budget_edit', 'reports:export'
    ],
  },
  {
    id: 'role-junior-accountant',
    name: 'Staff / Junior Accountant',
    code: 'junior_accountant',
    description: 'Draft journal entries, invoices, and bills subject to supervisory approval.',
    isSystemRole: true,
    permissions: ['journals:create', 'ar:manage', 'ap:manage'],
  },
  {
    id: 'role-auditor',
    name: 'External SOX / Compliance Auditor',
    code: 'auditor',
    description: 'Read-only access to double-entry ledger trails, cryptographic hashes, and audit reports.',
    isSystemRole: true,
    permissions: ['reports:export'],
  },
  {
    id: 'role-viewer',
    name: 'Executive Read-Only Viewer',
    code: 'viewer',
    description: 'Read-only access to high-level financial dashboards.',
    isSystemRole: true,
    permissions: [],
  },
];

export const INITIAL_ENTERPRISE_USERS: EnterpriseUser[] = [
  {
    id: 'usr-100',
    name: 'Alex Mercer',
    email: 'alex.superuser@platform.com',
    title: 'Global Systems Super Administrator',
    department: 'Global Technology & Governance',
    status: 'ACTIVE',
    mfaEnabled: true,
    defaultRole: 'super_user',
    tenantScopes: [
      { tenantId: 't-acme-us', role: 'super_user' },
      { tenantId: 't-global-eu', role: 'super_user' },
      { tenantId: 't-ind-corp', role: 'super_user' },
    ],
    lastLogin: '2026-08-13 02:00 UTC',
    createdAt: '2024-11-01',
    apiTokenCount: 5,
  },
  {
    id: 'usr-106',
    name: 'Maria Santos',
    email: 'maria.admin@acme-us.com',
    title: 'Acme US Corporate Entity Admin',
    department: 'Entity Administration',
    status: 'ACTIVE',
    mfaEnabled: true,
    defaultRole: 'entity_admin',
    tenantScopes: [
      { tenantId: 't-acme-us', role: 'entity_admin' },
    ],
    lastLogin: '2026-08-12 21:10 UTC',
    createdAt: '2025-03-15',
    apiTokenCount: 2,
  },
  {
    id: 'usr-107',
    name: 'Jean-Luc Picard',
    email: 'jean.admin@global-eu.com',
    title: 'EU Subsidiary Entity Admin',
    department: 'European Operations',
    status: 'ACTIVE',
    mfaEnabled: true,
    defaultRole: 'entity_admin',
    tenantScopes: [
      { tenantId: 't-global-eu', role: 'entity_admin' },
    ],
    lastLogin: '2026-08-12 16:22 UTC',
    createdAt: '2025-04-01',
    apiTokenCount: 1,
  },
  {
    id: 'usr-101',
    name: 'Johnathan Miller',
    email: 'john.admin@acme.com',
    title: 'Chief Financial Officer (CFO)',
    department: 'Executive Leadership',
    status: 'ACTIVE',
    mfaEnabled: true,
    defaultRole: 'admin',
    tenantScopes: [
      { tenantId: 't-acme-us', role: 'admin' },
      { tenantId: 't-global-eu', role: 'admin' },
      { tenantId: 't-ind-corp', role: 'admin' },
    ],
    lastLogin: '2026-08-13 01:15 UTC',
    createdAt: '2025-01-15',
    apiTokenCount: 3,
  },
  {
    id: 'usr-102',
    name: 'Sarah Jenkins',
    email: 'sarah.accountant@acme.com',
    title: 'Senior General Ledger Controller',
    department: 'Corporate Accounting',
    status: 'ACTIVE',
    mfaEnabled: true,
    defaultRole: 'controller',
    tenantScopes: [
      { tenantId: 't-acme-us', role: 'controller' },
      { tenantId: 't-global-eu', role: 'accountant' },
    ],
    lastLogin: '2026-08-12 18:40 UTC',
    createdAt: '2025-02-01',
    apiTokenCount: 1,
  },
  {
    id: 'usr-103',
    name: 'David Vance',
    email: 'david.junior@acme.com',
    title: 'Staff AP/AR Accountant',
    department: 'Finance Operations',
    status: 'ACTIVE',
    mfaEnabled: false,
    defaultRole: 'junior_accountant',
    tenantScopes: [
      { tenantId: 't-acme-us', role: 'junior_accountant' },
    ],
    lastLogin: '2026-08-11 09:12 UTC',
    createdAt: '2025-06-10',
    apiTokenCount: 0,
  },
  {
    id: 'usr-104',
    name: 'Elena Rostova',
    email: 'elena.auditor@kpmg-audit.com',
    title: 'Principal SOX 404 Lead Auditor',
    department: 'External Audit Advisory',
    status: 'ACTIVE',
    mfaEnabled: true,
    defaultRole: 'auditor',
    tenantScopes: [
      { tenantId: 't-acme-us', role: 'auditor' },
      { tenantId: 't-global-eu', role: 'auditor' },
    ],
    lastLogin: '2026-08-10 14:05 UTC',
    createdAt: '2026-01-10',
    apiTokenCount: 2,
  },
  {
    id: 'usr-105',
    name: 'Guest Viewer',
    email: 'guest.viewer@acme.com',
    title: 'Board Observer',
    department: 'Investor Relations',
    status: 'ACTIVE',
    mfaEnabled: false,
    defaultRole: 'viewer',
    tenantScopes: [
      { tenantId: 't-acme-us', role: 'viewer' },
    ],
    lastLogin: '2026-08-05 11:30 UTC',
    createdAt: '2026-03-20',
    apiTokenCount: 0,
  },
];

export const mockCustomAttributeDefinitions: import('./types').CustomAttributeDefinition[] = [
  // Housing Society Preset
  {
    id: 'attr-hs-1',
    tenantId: 't-acme-us',
    name: 'Unit / Flat Number',
    key: 'unit_number',
    dataType: 'text',
    targetEntity: 'CUSTOMER',
    industryPreset: 'HOUSING_SOCIETY',
    description: 'Flat, Apartment, or Villa Unit Identifier',
    isRequired: true,
  },
  {
    id: 'attr-hs-2',
    tenantId: 't-acme-us',
    name: 'Wing / Block Tower',
    key: 'wing_block',
    dataType: 'select',
    options: ['Tower A (Emerald)', 'Tower B (Sapphire)', 'Tower C (Ruby)', 'Villa Enclave'],
    targetEntity: 'CUSTOMER',
    industryPreset: 'HOUSING_SOCIETY',
    description: 'Residential Wing or Building Complex Section',
  },
  {
    id: 'attr-hs-3',
    tenantId: 't-acme-us',
    name: 'Carpet Area',
    key: 'carpet_area_sqft',
    dataType: 'decimal',
    unitOrSuffix: 'sq ft',
    targetEntity: 'CUSTOMER',
    industryPreset: 'HOUSING_SOCIETY',
    description: 'Registered super built-up/carpet area for monthly dues calculation',
    defaultValue: 1200,
  },
  {
    id: 'attr-hs-4',
    tenantId: 't-acme-us',
    name: 'Allocated Parking Bays',
    key: 'parking_slots',
    dataType: 'number',
    targetEntity: 'CUSTOMER',
    industryPreset: 'HOUSING_SOCIETY',
    description: 'Number of reserved basement/podium parking spots',
    defaultValue: 1,
  },
  {
    id: 'attr-hs-5',
    tenantId: 't-acme-us',
    name: 'Owner Occupied',
    key: 'is_owner_occupied',
    dataType: 'boolean',
    targetEntity: 'CUSTOMER',
    industryPreset: 'HOUSING_SOCIETY',
    description: 'Whether the unit is inhabited by registered owner vs tenant',
    defaultValue: true,
  },
  {
    id: 'attr-hs-6',
    tenantId: 't-acme-us',
    name: 'Monthly Maintenance Rate / SqFt',
    key: 'maintenance_rate_sqft',
    dataType: 'decimal',
    unitOrSuffix: '$/sq ft',
    targetEntity: 'CUSTOMER',
    industryPreset: 'HOUSING_SOCIETY',
    description: 'Standard monthly HOA/Society maintenance tariff per sq ft',
    defaultValue: 2.50,
  },
  {
    id: 'attr-hs-7',
    tenantId: 't-acme-us',
    name: 'Move-in / Possession Date',
    key: 'move_in_date',
    dataType: 'date',
    targetEntity: 'CUSTOMER',
    industryPreset: 'HOUSING_SOCIETY',
    description: 'Date of key handover and society membership activation',
  },

  // School / Educational Institution Preset
  {
    id: 'attr-sc-1',
    tenantId: 't-acme-us',
    name: 'Student Roll / Enrollment No',
    key: 'student_roll_no',
    dataType: 'text',
    targetEntity: 'CUSTOMER',
    industryPreset: 'SCHOOL',
    description: 'Unique student matriculation/enrollment code',
    isRequired: true,
  },
  {
    id: 'attr-sc-2',
    tenantId: 't-acme-us',
    name: 'Grade / Academic Batch',
    key: 'grade_batch',
    dataType: 'select',
    options: ['Kindergarten', 'Grade 5', 'Grade 8', 'Grade 10-IGCSE', 'Grade 11-STEM', 'Grade 12-AP Honors'],
    targetEntity: 'CUSTOMER',
    industryPreset: 'SCHOOL',
    description: 'Current academic level and section',
  },
  {
    id: 'attr-sc-3',
    tenantId: 't-acme-us',
    name: 'Dedicated Bus Transport Route',
    key: 'bus_route',
    dataType: 'select',
    options: ['Route 1 - Downtown Express', 'Route 2 - North Ridge', 'Route 3 - West Suburbs', 'Self Transport (No Bus)'],
    targetEntity: 'CUSTOMER',
    industryPreset: 'SCHOOL',
    description: 'Assigned school transit bus route',
  },
  {
    id: 'attr-sc-4',
    tenantId: 't-acme-us',
    name: 'Scholarship / Merit Discount',
    key: 'scholarship_discount_percent',
    dataType: 'decimal',
    unitOrSuffix: '%',
    targetEntity: 'CUSTOMER',
    industryPreset: 'SCHOOL',
    description: 'Tuition fee concession percentage approved by board',
    defaultValue: 0,
  },
  {
    id: 'attr-sc-5',
    tenantId: 't-acme-us',
    name: 'Hostel / Boarding Resident',
    key: 'is_hostel_resident',
    dataType: 'boolean',
    targetEntity: 'CUSTOMER',
    industryPreset: 'SCHOOL',
    description: 'Enrolled in on-campus boarding house dining & lodge',
    defaultValue: false,
  },

  // Hospital / Healthcare Clinic Preset
  {
    id: 'attr-hp-1',
    tenantId: 't-acme-us',
    name: 'Medical Record Number (MRN)',
    key: 'patient_mrn',
    dataType: 'text',
    targetEntity: 'CUSTOMER',
    industryPreset: 'HOSPITAL',
    description: 'Universal patient health record identifier',
    isRequired: true,
  },
  {
    id: 'attr-hp-2',
    tenantId: 't-acme-us',
    name: 'Admission Care Type',
    key: 'admission_type',
    dataType: 'select',
    options: ['Inpatient Care', 'ICU Critical', 'Day Surgery', 'Outpatient Consult', 'Emergency Trauma'],
    targetEntity: 'CUSTOMER',
    industryPreset: 'HOSPITAL',
    description: 'Clinical admission level and ward priority',
  },
  {
    id: 'attr-hp-3',
    tenantId: 't-acme-us',
    name: 'Assigned Ward & Bed Number',
    key: 'ward_bed_no',
    dataType: 'text',
    targetEntity: 'CUSTOMER',
    industryPreset: 'HOSPITAL',
    description: 'Hospital room or critical bed locator',
  },
  {
    id: 'attr-hp-4',
    tenantId: 't-acme-us',
    name: 'Attending Chief Physician',
    key: 'attending_physician',
    dataType: 'text',
    targetEntity: 'CUSTOMER',
    industryPreset: 'HOSPITAL',
    description: 'Lead medical consultant or surgeon responsible for case',
  },
  {
    id: 'attr-hp-5',
    tenantId: 't-acme-us',
    name: 'Insurance / TPA Policy Number',
    key: 'insurance_policy_no',
    dataType: 'text',
    targetEntity: 'CUSTOMER',
    industryPreset: 'HOSPITAL',
    description: 'Health insurance pre-authorization or claims ID',
  },
  {
    id: 'attr-hp-6',
    tenantId: 't-acme-us',
    name: 'Daily Bed Charge Tariff',
    key: 'daily_bed_tariff',
    dataType: 'decimal',
    unitOrSuffix: '$/day',
    targetEntity: 'CUSTOMER',
    industryPreset: 'HOSPITAL',
    description: 'Standard daily room charge tariff',
    defaultValue: 750,
  },

  // Enterprise / SaaS & General Preset
  {
    id: 'attr-sa-1',
    tenantId: 't-acme-us',
    name: 'Tax ID / GSTIN / VAT Reg',
    key: 'tax_reg_no',
    dataType: 'text',
    targetEntity: 'BOTH',
    industryPreset: 'SAAS',
    description: 'Official corporate statutory tax registration identifier',
  },
  {
    id: 'attr-sa-2',
    tenantId: 't-acme-us',
    name: 'Contract Service Level (SLA)',
    key: 'sla_tier',
    dataType: 'select',
    options: ['Standard 99.5% (Next Business Day)', 'Premium 99.9% (4-hr Response)', 'Mission-Critical 99.99% (15-min 24x7)'],
    targetEntity: 'CUSTOMER',
    industryPreset: 'SAAS',
    description: 'Contractual technical support and uptime guarantee tier',
  },
  {
    id: 'attr-sa-3',
    tenantId: 't-acme-us',
    name: 'Enterprise SSO Enforced',
    key: 'is_sso_enforced',
    dataType: 'boolean',
    targetEntity: 'CUSTOMER',
    industryPreset: 'SAAS',
    description: 'SAML 2.0 / Okta / Azure AD identity federation mandated',
    defaultValue: true,
  },
  {
    id: 'attr-sa-4',
    tenantId: 't-acme-us',
    name: 'Vendor AMC / Contract Expiry Date',
    key: 'contract_expiry_date',
    dataType: 'date',
    targetEntity: 'VENDOR',
    industryPreset: 'SAAS',
    description: 'Annual maintenance or SLA expiration milestone',
  },
];

export const mockCustomerContacts: import('./types').CustomerContact[] = [
  // Housing Society Resident Customer
  {
    id: 'cust-hs-101',
    tenantId: 't-acme-us',
    code: 'RES-A402',
    name: 'Alexander Sterling (Flat A-402)',
    email: 'a.sterling@residence.emerald.org',
    phone: '+1 (555) 782-9912',
    billingAddress: 'Unit A-402, Emerald Towers, 742 Evergreen Terrace',
    category: 'Housing Society Resident',
    status: 'ACTIVE',
    paymentTermsDays: 15,
    taxId: 'US-RES-9921',
    customAttributes: {
      unit_number: 'Flat A-402',
      wing_block: 'Tower A (Emerald)',
      carpet_area_sqft: 1450,
      parking_slots: 2,
      is_owner_occupied: true,
      maintenance_rate_sqft: 2.50,
      move_in_date: '2024-03-15',
    },
    notes: 'Society Board Secretary. Monthly maintenance invoices auto-debited on 1st.',
    createdAt: '2024-03-15',
  },
  // School Student Customer
  {
    id: 'cust-sc-102',
    tenantId: 't-acme-us',
    code: 'STU-2026-88',
    name: 'Maya Lin (Guardian: Richard Lin)',
    email: 'richard.lin@parentmail.com',
    phone: '+1 (555) 438-1120',
    billingAddress: '88 Oakridge Lane, Suburbia North',
    category: 'School Student',
    status: 'ACTIVE',
    paymentTermsDays: 30,
    customAttributes: {
      student_roll_no: 'STU-2026-88',
      grade_batch: 'Grade 11-STEM',
      bus_route: 'Route 1 - Downtown Express',
      scholarship_discount_percent: 10,
      is_hostel_resident: false,
    },
    notes: 'Honor Roll student in Advanced Physics. Fee concession applied to quarterly tuition.',
    createdAt: '2025-08-20',
  },
  // Hospital Inpatient Customer
  {
    id: 'cust-hp-103',
    tenantId: 't-acme-us',
    code: 'MRN-90452',
    name: 'Eleanor Vance (Patient MRN-90452)',
    email: 'evance.family@caremail.org',
    phone: '+1 (555) 321-7788',
    billingAddress: '414 Sycamore Blvd, Metro Central',
    category: 'Hospital Inpatient',
    status: 'ACTIVE',
    paymentTermsDays: 10,
    customAttributes: {
      patient_mrn: 'MRN-90452',
      admission_type: 'Inpatient Care',
      ward_bed_no: 'Deluxe Ward 304',
      attending_physician: 'Dr. Robert Chen, MD (Cardiology)',
      insurance_policy_no: 'BLUE-CROSS-PPO-884210',
      daily_bed_tariff: 850.00,
    },
    notes: 'Post-cardiac rehab care. 80% cashless coverage pre-approved by Blue Cross.',
    createdAt: '2026-08-01',
  },
  // Enterprise Tech Client Customer
  {
    id: 'cust-corp-104',
    tenantId: 't-acme-us',
    code: 'CUST-ACME-90',
    name: 'Vanguard Global Financial LLC',
    email: 'finance.ap@vanguardglobal.com',
    phone: '+1 (212) 555-0199',
    billingAddress: '100 Wall Street, Suite 4400, New York, NY 10005',
    category: 'Enterprise Client',
    status: 'ACTIVE',
    paymentTermsDays: 45,
    taxId: 'US-EIN-13-8874102',
    customAttributes: {
      tax_reg_no: 'US-EIN-13-8874102',
      sla_tier: 'Mission-Critical 99.99% (15-min 24x7)',
      is_sso_enforced: true,
    },
    notes: 'Tier-1 enterprise SaaS customer. Dedicated TAM and quarterly business review.',
    createdAt: '2024-01-10',
  },
  {
    id: 'cust-corp-105',
    tenantId: 't-acme-us',
    code: 'CUST-STRL-01',
    name: 'Starlight Financial Corp',
    email: 'billing@starlight.com',
    phone: '+1 (415) 555-8831',
    billingAddress: '555 California St, Suite 2200, San Francisco, CA 94104',
    category: 'Enterprise Client',
    status: 'ACTIVE',
    paymentTermsDays: 30,
    taxId: 'US-EIN-94-3329104',
    customAttributes: {
      tax_reg_no: 'US-EIN-94-3329104',
      sla_tier: 'Standard Enterprise SLA',
      is_sso_enforced: true,
    },
    notes: 'Fintech partner. Annual software license billed annually.',
    createdAt: '2024-02-01',
  },
  {
    id: 'cust-corp-106',
    tenantId: 't-acme-us',
    code: 'CUST-APEX-02',
    name: 'Apex Logistics Inc',
    email: 'ap@apexlogistics.com',
    phone: '+1 (312) 555-4920',
    billingAddress: '200 S Wacker Dr, Chicago, IL 60606',
    category: 'Enterprise Client',
    status: 'ACTIVE',
    paymentTermsDays: 30,
    taxId: 'US-EIN-36-8849102',
    customAttributes: {
      tax_reg_no: 'US-EIN-36-8849102',
      sla_tier: 'Standard Enterprise SLA',
      is_sso_enforced: false,
    },
    notes: 'National logistics fleet. Periodic consulting and audit automation.',
    createdAt: '2024-05-15',
  },
];

export const mockVendorContacts: import('./types').VendorContact[] = [
  // Housing Society Lift & Security Vendor
  {
    id: 'vend-hs-201',
    tenantId: 't-acme-us',
    code: 'VEND-OTIS-01',
    name: 'Otis Elevator AMC & Maintenance Corp',
    email: 'service.contracts@otis-elevators.com',
    phone: '+1 (800) 555-6847',
    address: 'One Carrier Place, Farmington, CT 06032',
    category: 'Facility & Lift AMC',
    status: 'ACTIVE',
    defaultExpenseAccountCode: '5030',
    paymentTermsDays: 30,
    taxId: 'US-EIN-06-0382910',
    customAttributes: {
      tax_reg_no: 'US-EIN-06-0382910',
      contract_expiry_date: '2027-04-30',
    },
    bankDetails: {
      bankName: 'JPMorgan Chase NY',
      accountNumber: '9982441029',
      routingNumber: '021000021',
    },
    notes: 'Quarterly preventative safety audit and emergency 24/7 rescue service included.',
    createdAt: '2024-04-01',
  },
  // School Transport Vendor
  {
    id: 'vend-sc-202',
    tenantId: 't-acme-us',
    code: 'VEND-FIRST-TRANS',
    name: 'First Student Transit Logistics LLC',
    email: 'fleet.billing@firststudent.com',
    phone: '+1 (800) 555-2877',
    address: '600 Vine St, Suite 1400, Cincinnati, OH 45202',
    category: 'Student Bus Transport',
    status: 'ACTIVE',
    defaultExpenseAccountCode: '5030',
    paymentTermsDays: 15,
    taxId: 'US-EIN-31-0987654',
    customAttributes: {
      tax_reg_no: 'US-EIN-31-0987654',
      contract_expiry_date: '2026-12-31',
    },
    bankDetails: {
      bankName: 'PNC Bank Ohio',
      accountNumber: '8872019941',
      routingNumber: '042000013',
    },
    notes: 'Operating 12 yellow school bus routes with real-time GPS telemetry.',
    createdAt: '2024-08-10',
  },
  // Hospital Pharma Supplies Vendor
  {
    id: 'vend-hp-203',
    tenantId: 't-acme-us',
    code: 'VEND-MEDTRONIC',
    name: 'Medtronic Surgical & Pharma Supplies Inc',
    email: 'hospital.orders@medtronic.com',
    phone: '+1 (800) 555-6338',
    address: '710 Medtronic Pkwy, Minneapolis, MN 55432',
    category: 'Medical Devices & Pharma',
    status: 'ACTIVE',
    defaultExpenseAccountCode: '5010',
    paymentTermsDays: 30,
    taxId: 'US-EIN-41-0793280',
    customAttributes: {
      tax_reg_no: 'US-EIN-41-0793280',
      contract_expiry_date: '2027-06-30',
    },
    bankDetails: {
      bankName: 'U.S. Bank Minneapolis',
      accountNumber: '5510293847',
      routingNumber: '091000019',
    },
    notes: 'FDA-certified medical consumable supplies, cardiac stents, and surgical kits.',
    createdAt: '2024-02-15',
  },
  // Enterprise Cloud Hosting Vendor
  {
    id: 'vend-corp-204',
    tenantId: 't-acme-us',
    code: 'VEND-AWS-01',
    name: 'Amazon Web Services Cloud Infrastructure',
    email: 'aws-invoicing@amazon.com',
    phone: '+1 (206) 555-0100',
    address: '410 Terry Ave N, Seattle, WA 98109',
    category: 'Cloud Infrastructure',
    status: 'ACTIVE',
    defaultExpenseAccountCode: '5010',
    paymentTermsDays: 30,
    taxId: 'US-EIN-91-1646860',
    customAttributes: {
      tax_reg_no: 'US-EIN-91-1646860',
      contract_expiry_date: '2028-12-31',
    },
    bankDetails: {
      bankName: 'Wells Fargo San Francisco',
      accountNumber: '1109283746',
      routingNumber: '121000247',
    },
    notes: 'Primary data center cloud computing and database hosting.',
    createdAt: '2023-01-01',
  },
];

export const mockProductServices: import('./types').ProductServiceItem[] = [
  // 1. Enterprise SaaS & Professional Services
  {
    id: 'prod-saas-101',
    tenantId: 't-acme-us',
    code: 'PRD-SAAS-ENT',
    name: 'Enterprise Platform Annual License',
    description: 'Full multi-entity accounting suite with automated GL consolidation, bank sync, and audit trails.',
    type: 'PRODUCT',
    category: 'Software License',
    unitPrice: 10000,
    unitOfMeasure: 'year',
    defaultTaxRate: 10,
    defaultRevenueAccountCode: '4010',
    status: 'ACTIVE',
    createdAt: '2025-01-10',
    lastPriceUpdatedAt: '2026-01-15',
    lastPriceUpdatedBy: 'john.admin@acme.com',
    lastPriceChangeReason: 'Annual contract indexation & v2.0 Multi-Entity AI feature release',
  },
  {
    id: 'prod-saas-102',
    tenantId: 't-acme-us',
    code: 'PRD-SEAT-USR',
    name: 'User License - Per Seat (Monthly)',
    description: 'Individual employee named access seat with RBAC permission controls.',
    type: 'PRODUCT',
    category: 'Software License',
    unitPrice: 75,
    unitOfMeasure: 'user/mo',
    defaultTaxRate: 10,
    defaultRevenueAccountCode: '4010',
    status: 'ACTIVE',
    createdAt: '2025-01-15',
    lastPriceUpdatedAt: '2026-02-01',
    lastPriceUpdatedBy: 'sarah.accountant@acme.com',
    lastPriceChangeReason: 'Standard tier realignment with market cloud compute costs',
  },
  {
    id: 'prod-srv-103',
    tenantId: 't-acme-us',
    code: 'SRV-ARCH-CONS',
    name: 'Solutions Architecture & ERP Integration',
    description: 'Expert implementation consulting, data migration, and custom GL schema setup.',
    type: 'SERVICE',
    category: 'Professional Services',
    unitPrice: 250,
    unitOfMeasure: 'hour',
    defaultTaxRate: 10,
    defaultRevenueAccountCode: '4020',
    status: 'ACTIVE',
    createdAt: '2025-02-01',
    lastPriceUpdatedAt: '2026-03-01',
    lastPriceUpdatedBy: 'john.admin@acme.com',
    lastPriceChangeReason: 'Principal architect billable rate adjustment',
  },
  {
    id: 'prod-srv-104',
    tenantId: 't-acme-us',
    code: 'SRV-AUDIT-SOX',
    name: 'SOX 404 & SOC 2 Compliance Audit Prep',
    description: 'Independent internal control evaluation, audit trail export, and remediation.',
    type: 'SERVICE',
    category: 'Advisory & Audit',
    unitPrice: 15000,
    unitOfMeasure: 'audit',
    defaultTaxRate: 10,
    defaultRevenueAccountCode: '4020',
    status: 'ACTIVE',
    createdAt: '2025-02-15',
  },

  // 2. Housing Society / HOA Archetype Items
  {
    id: 'prod-hs-201',
    tenantId: 't-acme-us',
    code: 'SRV-MAINT-SQFT',
    name: 'Society Monthly Maintenance Assessment',
    description: 'Common area maintenance, 24/7 security, power backup, and landscaped gardening billed per sq ft carpet area.',
    type: 'SERVICE',
    category: 'HOA Maintenance',
    unitPrice: 1.75,
    unitOfMeasure: 'sq ft',
    defaultTaxRate: 5,
    defaultRevenueAccountCode: '4010',
    status: 'ACTIVE',
    createdAt: '2025-01-01',
  },
  {
    id: 'prod-hs-202',
    tenantId: 't-acme-us',
    code: 'SRV-PARK-BAY',
    name: 'Basement Parking Bay Maintenance Charge',
    description: 'Dedicated covered automobile parking bay upkeep and ventilation fee.',
    type: 'SERVICE',
    category: 'HOA Maintenance',
    unitPrice: 60,
    unitOfMeasure: 'bay/mo',
    defaultTaxRate: 5,
    defaultRevenueAccountCode: '4010',
    status: 'ACTIVE',
    createdAt: '2025-01-01',
  },
  {
    id: 'prod-hs-203',
    tenantId: 't-acme-us',
    code: 'SRV-CLUB-EVENT',
    name: 'Clubhouse Banquet Hall Reservation',
    description: 'Private community hall booking for family gatherings and member celebrations.',
    type: 'SERVICE',
    category: 'Amenities & Rentals',
    unitPrice: 500,
    unitOfMeasure: 'event/day',
    defaultTaxRate: 10,
    defaultRevenueAccountCode: '4020',
    status: 'ACTIVE',
    createdAt: '2025-03-01',
  },
  {
    id: 'prod-hs-204',
    tenantId: 't-acme-us',
    code: 'PRD-EV-PWR',
    name: 'EV Charging Station Electric Consumption',
    description: 'Sub-metered electric vehicle charging power consumption.',
    type: 'PRODUCT',
    category: 'Utilities',
    unitPrice: 0.22,
    unitOfMeasure: 'kWh',
    defaultTaxRate: 5,
    defaultRevenueAccountCode: '4010',
    status: 'ACTIVE',
    createdAt: '2025-03-15',
  },

  // 3. School & University Archetype Items
  {
    id: 'prod-sch-301',
    tenantId: 't-acme-us',
    code: 'SRV-TUIT-TERM',
    name: 'Academic Tuition & Faculty Instruction',
    description: 'Curriculum instruction, classroom instruction, and semester examinations.',
    type: 'SERVICE',
    category: 'Education Tuition',
    unitPrice: 3500,
    unitOfMeasure: 'term',
    defaultTaxRate: 0,
    defaultRevenueAccountCode: '4010',
    status: 'ACTIVE',
    createdAt: '2025-01-01',
  },
  {
    id: 'prod-sch-302',
    tenantId: 't-acme-us',
    code: 'SRV-BUS-TRANS',
    name: 'School Yellow Bus Transport Route',
    description: 'Doorstep daily air-conditioned bus transportation with RFID attendance.',
    type: 'SERVICE',
    category: 'Student Transport',
    unitPrice: 450,
    unitOfMeasure: 'term',
    defaultTaxRate: 0,
    defaultRevenueAccountCode: '4010',
    status: 'ACTIVE',
    createdAt: '2025-01-01',
  },
  {
    id: 'prod-sch-303',
    tenantId: 't-acme-us',
    code: 'SRV-STEM-ROBOT',
    name: 'STEM Robotics & Coding Lab Access',
    description: 'Hands-on practical kits, hardware components, and coding workshops.',
    type: 'SERVICE',
    category: 'Lab Fees',
    unitPrice: 300,
    unitOfMeasure: 'term',
    defaultTaxRate: 0,
    defaultRevenueAccountCode: '4020',
    status: 'ACTIVE',
    createdAt: '2025-02-01',
  },
  {
    id: 'prod-sch-304',
    tenantId: 't-acme-us',
    code: 'PRD-UNIF-KIT',
    name: 'Student Blazer & Uniform Set',
    description: 'Official school crest blazer, shirts, trousers, and sports kit.',
    type: 'PRODUCT',
    category: 'Uniforms & Goods',
    unitPrice: 180,
    unitOfMeasure: 'set',
    defaultTaxRate: 5,
    defaultRevenueAccountCode: '4010',
    status: 'ACTIVE',
    createdAt: '2025-02-10',
  },

  // 4. Hospital & Healthcare Clinic Archetype Items
  {
    id: 'prod-hosp-401',
    tenantId: 't-acme-us',
    code: 'SRV-SPEC-CONS',
    name: 'Specialist Physician Consultation',
    description: 'Senior attending specialist outpatient or inpatient diagnostic consultation.',
    type: 'SERVICE',
    category: 'Medical Services',
    unitPrice: 250,
    unitOfMeasure: 'session',
    defaultTaxRate: 0,
    defaultRevenueAccountCode: '4020',
    status: 'ACTIVE',
    createdAt: '2025-01-01',
  },
  {
    id: 'prod-hosp-402',
    tenantId: 't-acme-us',
    code: 'SRV-BED-WARD',
    name: 'Inpatient Private Deluxe Room & Nursing',
    description: 'Private patient suite with 24/7 dedicated nursing monitoring and dietary meals.',
    type: 'SERVICE',
    category: 'Room & Bed Tariff',
    unitPrice: 350,
    unitOfMeasure: 'day',
    defaultTaxRate: 0,
    defaultRevenueAccountCode: '4010',
    status: 'ACTIVE',
    createdAt: '2025-01-01',
  },
  {
    id: 'prod-hosp-403',
    tenantId: 't-acme-us',
    code: 'SRV-MRI-SCAN',
    name: 'High-Field 3T Diagnostic MRI Scan',
    description: 'Full neuro / orthopedic magnetic resonance imaging with radiologist report.',
    type: 'SERVICE',
    category: 'Diagnostics & Labs',
    unitPrice: 850,
    unitOfMeasure: 'procedure',
    defaultTaxRate: 0,
    defaultRevenueAccountCode: '4020',
    status: 'ACTIVE',
    createdAt: '2025-01-10',
  },
  {
    id: 'prod-hosp-404',
    tenantId: 't-acme-us',
    code: 'PRD-SURG-PACK',
    name: 'Sterile Surgical Consumables & Post-Op Kit',
    description: 'Surgical dressings, antiseptic sutures, and single-use sterile instrumentation.',
    type: 'PRODUCT',
    category: 'Pharma & Supplies',
    unitPrice: 420,
    unitOfMeasure: 'pack',
    defaultTaxRate: 5,
    defaultRevenueAccountCode: '4010',
    status: 'ACTIVE',
    createdAt: '2025-01-15',
  },
];

export const mockPriceChangeHistory: import('./types').PriceChangeHistoryEntry[] = [
  {
    id: 'pch-1001',
    itemId: 'prod-saas-101',
    itemCode: 'PRD-SAAS-ENT',
    itemName: 'Enterprise Platform Annual License',
    tenantId: 't-acme-us',
    oldPrice: 8500,
    newPrice: 10000,
    currency: 'USD',
    changeDate: '2026-01-15T09:30:00Z',
    effectiveDate: '2026-02-01',
    changedBy: 'john.admin@acme.com',
    changedRole: 'admin',
    reason: 'Annual contract indexation & v2.0 Multi-Entity AI feature release',
    changePercentage: 17.65,
    notes: 'Approved by CFO in Q1 Operating Committee meeting minutes.',
  },
  {
    id: 'prod-pch-1002',
    itemId: 'prod-saas-102',
    itemCode: 'PRD-SEAT-USR',
    itemName: 'User License - Per Seat (Monthly)',
    tenantId: 't-acme-us',
    oldPrice: 65,
    newPrice: 75,
    currency: 'USD',
    changeDate: '2026-02-01T14:15:00Z',
    effectiveDate: '2026-02-15',
    changedBy: 'sarah.accountant@acme.com',
    changedRole: 'accountant',
    reason: 'Standard tier realignment with market cloud compute costs',
    changePercentage: 15.38,
    notes: 'Updated across all new sales proposals.',
  },
  {
    id: 'prod-pch-1003',
    itemId: 'prod-srv-103',
    itemCode: 'SRV-ARCH-CONS',
    itemName: 'Solutions Architecture & ERP Integration',
    tenantId: 't-acme-us',
    oldPrice: 220,
    newPrice: 250,
    currency: 'USD',
    changeDate: '2026-03-01T11:00:00Z',
    effectiveDate: '2026-03-01',
    changedBy: 'john.admin@acme.com',
    changedRole: 'admin',
    reason: 'Principal architect billable rate adjustment',
    changePercentage: 13.64,
    notes: 'Reviewed by professional services practice director.',
  },
  {
    id: 'prod-pch-1004',
    itemId: 'prod-hs-201',
    itemCode: 'SRV-MAINT-SQFT',
    itemName: 'Society Monthly Maintenance Assessment',
    tenantId: 't-acme-us',
    oldPrice: 1.50,
    newPrice: 1.75,
    currency: 'USD',
    changeDate: '2026-04-01T10:00:00Z',
    effectiveDate: '2026-04-01',
    changedBy: 'maria.admin@acme-us.com',
    changedRole: 'entity_admin',
    reason: 'Annual General Meeting (AGM) Resolution #4: Escalation for 24/7 security wages & diesel generator backup fuel',
    changePercentage: 16.67,
    notes: 'Notified to all apartment owners via AGM circular.',
  },
  {
    id: 'prod-pch-1005',
    itemId: 'prod-sch-301',
    itemCode: 'SRV-TUIT-TERM',
    itemName: 'Academic Tuition & Faculty Instruction',
    tenantId: 't-acme-us',
    oldPrice: 3200,
    newPrice: 3500,
    currency: 'USD',
    changeDate: '2026-05-15T08:45:00Z',
    effectiveDate: '2026-08-01',
    changedBy: 'sarah.accountant@acme.com',
    changedRole: 'accountant',
    reason: 'Academic Council approved semester tuition tariff revision',
    changePercentage: 9.38,
    notes: 'Applicable for Fall 2026 term enrollment.',
  },
];

export const mockInvoiceTemplates: InvoiceTemplate[] = [
  {
    id: 'tmpl-saas-enterprise',
    tenantId: 't-acme-us',
    code: 'TMPL-SAAS-ANNUAL',
    name: 'Enterprise SaaS Annual Subscription & Premium SLA Bundle',
    description: 'Complete annual SaaS tier license with user license packs, dedicated Technical Account Manager, and 99.99% SLA.',
    category: 'SaaS & Subscriptions',
    defaultPaymentTermsDays: 30,
    defaultRevenueAccountCode: '4010',
    defaultNotes: 'Annual platform subscription billed in advance. Payment due NET 30 via ACH/Wire. Renewal subject to MSA terms.',
    isActive: true,
    createdAt: '2026-01-15T09:00:00Z',
    updatedAt: '2026-05-10T14:30:00Z',
    usageCount: 24,
    items: [
      {
        id: 'tmpl-item-101',
        productId: 'prod-saas-101',
        productCode: 'PRD-SAAS-ENT',
        description: 'Enterprise Cloud Platform Core Tenant License (Annual Subscription)',
        quantity: 1,
        unitPrice: 28000,
        taxRate: 10,
        unitOfMeasure: 'year',
        amount: 28000,
      },
      {
        id: 'tmpl-item-102',
        productId: 'prod-saas-102',
        productCode: 'PRD-SEAT-LIC',
        description: 'Enterprise User Seat License Add-on (50-User Pack)',
        quantity: 2,
        unitPrice: 4500,
        taxRate: 10,
        unitOfMeasure: 'pack/yr',
        amount: 9000,
      },
      {
        id: 'tmpl-item-103',
        productId: 'prod-srv-104',
        productCode: 'SRV-SLA-PREM',
        description: 'Dedicated 24/7 Technical Account Manager & 15-Minute SLA Guarantee',
        quantity: 1,
        unitPrice: 6000,
        taxRate: 10,
        unitOfMeasure: 'year',
        amount: 6000,
      },
    ],
  },
  {
    id: 'tmpl-consult-sprint',
    tenantId: 't-acme-us',
    code: 'TMPL-CONSULT-SPRINT',
    name: 'Bi-Weekly Agile Architecture & Cloud Engineering Sprint',
    description: 'Standard 2-week agile sprint delivery including principal architect leadership, full-stack dev hours, and automated QA security tests.',
    category: 'Professional Services',
    defaultPaymentTermsDays: 15,
    defaultRevenueAccountCode: '4020',
    defaultNotes: 'Milestone sprint delivery billable against approved Jira timesheets. Net 15 days payment.',
    isActive: true,
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-06-18T16:00:00Z',
    usageCount: 18,
    items: [
      {
        id: 'tmpl-item-201',
        productId: 'prod-srv-101',
        productCode: 'SRV-ARCH-HR',
        description: 'Principal Solutions Architect Advisory, High-Level Design & Code Review',
        quantity: 40,
        unitPrice: 250,
        taxRate: 10,
        unitOfMeasure: 'hour',
        amount: 10000,
      },
      {
        id: 'tmpl-item-202',
        productId: 'prod-srv-102',
        productCode: 'SRV-DEV-HR',
        description: 'Senior Full-Stack Cloud Development & Microservices Engineering',
        quantity: 80,
        unitPrice: 150,
        taxRate: 10,
        unitOfMeasure: 'hour',
        amount: 12000,
      },
      {
        id: 'tmpl-item-203',
        productCode: 'SRV-QA-SEC',
        description: 'Automated CI/CD Test Pipeline & Security Penetration Testing Suite',
        quantity: 20,
        unitPrice: 125,
        taxRate: 10,
        unitOfMeasure: 'hour',
        amount: 2500,
      },
    ],
  },
  {
    id: 'tmpl-society-commercial',
    tenantId: 't-acme-us',
    code: 'TMPL-SOCIETY-COMMERCIAL',
    name: 'Housing Society Commercial Unit Maintenance & HVAC Surcharge',
    description: 'Commercial shop & office space monthly maintenance assessment including high-capacity commercial power backup, HVAC chillers, customer parking, and waste management surcharge.',
    category: 'Property & Facilities',
    defaultPaymentTermsDays: 15,
    defaultRevenueAccountCode: '4010',
    defaultNotes: 'Commercial establishment quarterly maintenance. High-usage commercial surcharge included. Net 15 days.',
    isActive: true,
    createdAt: '2026-03-15T10:00:00Z',
    updatedAt: '2026-04-01T08:00:00Z',
    usageCount: 28,
    items: [
      {
        id: 'tmpl-item-comm-1',
        productId: 'prod-hs-201',
        productCode: 'SRV-MAINT-SQFT',
        description: 'Commercial Space Base Maintenance Tariff (Per Sq Ft Area)',
        quantity: 2400,
        unitPrice: 3.25,
        taxRate: 18,
        unitOfMeasure: 'sq ft',
        amount: 7800,
      },
      {
        id: 'tmpl-item-comm-2',
        productId: 'prod-hs-202',
        productCode: 'SRV-PARK-BAY',
        description: 'Commercial Dedicated Customer & Staff Parking Slots (4 Bays)',
        quantity: 4,
        unitPrice: 120,
        taxRate: 18,
        unitOfMeasure: 'bay/mo',
        amount: 480,
      },
      {
        id: 'tmpl-item-comm-3',
        productCode: 'SRV-COMM-HVAC',
        description: 'Commercial Central Air Conditioning Chiller & High Load Diesel Generator Surcharge',
        quantity: 1,
        unitPrice: 650,
        taxRate: 18,
        unitOfMeasure: 'month',
        amount: 650,
      },
    ],
  },
  {
    id: 'tmpl-society-maint',
    tenantId: 't-acme-us',
    code: 'TMPL-SOCIETY-QTR',
    name: 'Housing Society Quarterly Maintenance Assessment & Sinking Fund',
    description: 'Standard residential quarterly bill including common area upkeep, 24/7 security wages, lift maintenance, parking bay, and capital sinking fund.',
    category: 'Property & Facilities',
    defaultPaymentTermsDays: 15,
    defaultRevenueAccountCode: '4010',
    defaultNotes: 'Quarterly housing society assessment. Dues payable by 15th of the billing month. Late fee of 1.5%/month applies after due date.',
    isActive: true,
    createdAt: '2026-03-10T11:30:00Z',
    updatedAt: '2026-04-01T08:00:00Z',
    usageCount: 42,
    items: [
      {
        id: 'tmpl-item-301',
        productId: 'prod-hs-201',
        productCode: 'SRV-MAINT-SQFT',
        description: 'Common Area Maintenance Assessment (1,850 sq ft unit base)',
        quantity: 1850,
        unitPrice: 1.75,
        taxRate: 5,
        unitOfMeasure: 'sq ft',
        amount: 3237.5,
      },
      {
        id: 'tmpl-item-302',
        productId: 'prod-hs-202',
        productCode: 'SRV-PARK-BAY',
        description: 'Covered Basement Resident Parking Bay Maintenance (2 Assigned Bays)',
        quantity: 2,
        unitPrice: 50,
        taxRate: 5,
        unitOfMeasure: 'bay/mo',
        amount: 100,
      },
      {
        id: 'tmpl-item-303',
        productId: 'prod-hs-203',
        productCode: 'SRV-SINK-FUND',
        description: 'Mandatory Society Infrastructure Capital Replacement & Sinking Fund',
        quantity: 1,
        unitPrice: 250,
        taxRate: 0,
        unitOfMeasure: 'quarter',
        amount: 250,
      },
    ],
  },
  {
    id: 'tmpl-edu-semester',
    tenantId: 't-acme-us',
    code: 'TMPL-EDU-SEMESTER',
    name: 'University Academic Semester Tuition & Laboratory Package',
    description: 'Comprehensive undergraduate tuition fee, computing lab cluster access, library resources, and athletics union fee.',
    category: 'Education',
    defaultPaymentTermsDays: 30,
    defaultRevenueAccountCode: '4010',
    defaultNotes: 'Academic semester fee statement. Installment plan available upon approval by the University Bursar Office.',
    isActive: true,
    createdAt: '2026-04-05T14:00:00Z',
    updatedAt: '2026-05-15T09:00:00Z',
    usageCount: 31,
    items: [
      {
        id: 'tmpl-item-401',
        productId: 'prod-sch-301',
        productCode: 'SRV-TUIT-TERM',
        description: 'Academic Term Tuition & Faculty Instruction (16 Credit Hours Enrolled)',
        quantity: 1,
        unitPrice: 3500,
        taxRate: 0,
        unitOfMeasure: 'term',
        amount: 3500,
      },
      {
        id: 'tmpl-item-402',
        productId: 'prod-sch-302',
        productCode: 'SRV-LAB-ACCESS',
        description: 'Advanced Computing Cloud Lab & Engineering Workshop Access',
        quantity: 1,
        unitPrice: 450,
        taxRate: 0,
        unitOfMeasure: 'term',
        amount: 450,
      },
      {
        id: 'tmpl-item-403',
        productCode: 'SRV-CAMPUS-FEE',
        description: 'Campus Student Union, Medical Center & Athletics Facility Levy',
        quantity: 1,
        unitPrice: 150,
        taxRate: 0,
        unitOfMeasure: 'term',
        amount: 150,
      },
    ],
  },
  {
    id: 'tmpl-health-corp',
    tenantId: 't-acme-us',
    code: 'TMPL-HEALTH-CORP',
    name: 'Corporate Annual Executive Wellness & Diagnostic Health Screening',
    description: 'Standard corporate employee cohort preventive health screening with comprehensive pathology lab tests and physician consultation.',
    category: 'Healthcare',
    defaultPaymentTermsDays: 30,
    defaultRevenueAccountCode: '4020',
    defaultNotes: 'Corporate wellness screening package. Aggregate diagnostic reporting provided to HR within 10 business days.',
    isActive: true,
    createdAt: '2026-05-02T11:00:00Z',
    updatedAt: '2026-06-20T10:00:00Z',
    usageCount: 15,
    items: [
      {
        id: 'tmpl-item-501',
        productId: 'prod-hc-401',
        productCode: 'SRV-HEALTH-CHECK',
        description: 'Executive Full-Body Preventive Health Checkup & Diagnostic Blood Chemistry Panel',
        quantity: 25,
        unitPrice: 320,
        taxRate: 5,
        unitOfMeasure: 'patient',
        amount: 8000,
      },
      {
        id: 'tmpl-item-502',
        productId: 'prod-hc-402',
        productCode: 'SRV-ERGO-ONSITE',
        description: 'On-site Corporate Ergonomics Audit & Occupational Physician Consultation Session',
        quantity: 2,
        unitPrice: 750,
        taxRate: 5,
        unitOfMeasure: 'session',
        amount: 1500,
      },
    ],
  },
];

export const INITIAL_BULK_BATCHES: import('./types').BulkInvoiceBatchRun[] = [
  {
    id: 'bat-2026-07-001',
    batchNumber: 'BAT-2026-07-001',
    tenantId: 't-acme-us',
    title: 'July 2026 Society Maintenance & Commercial Surcharge Run',
    createdAt: '2026-07-01T08:00:00.000Z',
    createdBy: 'sarah.accountant@acme.com',
    groupingAttributeKey: 'is_commercial',
    groupingAttributeName: 'Is Commercial Member (Boolean)',
    groupsCount: 2,
    totalCustomers: 8,
    totalInvoicesGenerated: 8,
    totalBatchAmount: 48925.0,
    totalTaxAmount: 4892.5,
    generatedInvoiceIds: ['inv-2026-07-01', 'inv-2026-07-02'],
    status: 'COMMITTED',
    groupBreakdowns: [
      {
        groupId: 'grp-is_commercial-true',
        groupName: 'Commercial Establishments (IsCommercial: True)',
        templateCode: 'TMPL-SOCIETY-COMMERCIAL',
        templateName: 'Housing Society Commercial Unit Maintenance & HVAC Surcharge',
        customerCount: 3,
        groupTotalAmount: 26790.0,
      },
      {
        groupId: 'grp-is_commercial-false',
        groupName: 'Residential Members (IsCommercial: False)',
        templateCode: 'TMPL-SOCIETY-QTR',
        templateName: 'Housing Society Quarterly Maintenance Assessment & Sinking Fund',
        customerCount: 5,
        groupTotalAmount: 22135.0,
      },
    ],
  },
];




